use_frameworks!

target 'SwiftBackgroundLocation_Example' do
  pod 'SwiftBackgroundLocation', :path => '../'

  target 'SwiftBackgroundLocation_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2'
    pod 'Nimble', '~> 7.0'
  end
end
